### ISSUE TITLE
dataverse entry needs to be approved to modify data

### ISSUE THREAD

**Issue by audiracmichelle** [NSAPH-Data-Processing/zip2county_master_xwalk#24]

**Comment by audiracmichelle** [comment]
I figured out that the reviewer can "return the dataset" to the dataset creator in order to allow him to make additional changes @jckitch. Let me know if you received a dataverse notification

**Comment by jckitch** [comment]
Got the dataverse notification @audiracmichelle and I'll work on incorporating the new datasets before the presentation next Wednesday.
